# Generated by Django 4.0.5 on 2022-06-28 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('three_six', '0001_initial'),
        ('ambiance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('date_of_birth', models.DateField()),
                ('profil', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('ambiance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambiance.ambiance')),
                ('langage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='three_six.langage')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='three_six.letter')),
                ('mathe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='three_six.math')),
                ('pratique_life', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='three_six.practicallife')),
                ('sensorial_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='three_six.sensorymaterial')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
