# Generated by Django 4.0.5 on 2022-06-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BOIS', 'Bois'), ('TERRE', 'Terre')], max_length=20, verbose_name='Ambiance')),
                ('year', models.CharField(max_length=20, verbose_name='Année')),
            ],
        ),
    ]
