# Generated by Django 4.0.5 on 2022-07-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students_active'),
        ('authentication', '0001_initial'),
        ('ambiance', '0002_ambiance_date_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ambiance',
            new_name='Environment',
        ),
    ]
