# Generated by Django 4.0.5 on 2022-06-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three_six', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='langage',
            name='title_4',
            field=models.CharField(default='ETUDE DE MOT', max_length=100),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_a',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_b',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='B'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_c',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='C'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_d',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='D'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_e',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='E'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_f',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='F'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_g',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='G'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_h',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='H'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_i',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='I'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_j',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='J'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_k',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='K'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_l',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='L'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_m',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='M'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_n',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='N'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_o',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='O'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_p',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='P'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_q',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='Q'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_r',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='R'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_s',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='S'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_t',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='T'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_u',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='U'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_v',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='V'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_w',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='W'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_x',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_y',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='Y'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_z',
            field=models.CharField(choices=[('presented', 'Présentée'), ('traced', 'tracée'), ('heard', 'Entendue'), ('read', 'Lue'), ('written', 'Ecrite')], max_length=100, verbose_name='Z'),
        ),
    ]
